server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: http://192.168.246.1:8001
#          uri: http://PRIVDER-PAYMENT-SERVICE
          predicates:
            - Path=/payment/** # 断言，路径相匹配的进行路由
        - id: payment_route2
          uri: http://192.168.246.1:8001
#          uri: http://PRIVDER-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7001/eureka/