server:
  port: 80

eureka:
  client:
    #    把自己注册到eurekaServer
    register-with-eureka: true
    #    是否从eurekaService 抓取自己的注册信息,默认为true,单点无所谓,集群是设置为true,才能配合Robbie负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7001/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true